<a href="https://colab.research.google.com/github/d93y70123123/AI/blob/master/OpenCV_0514.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import cv2

In [9]:
#!wget https://raw.githubusercontent.com/MyDearGreatTeacher/AISec_2020/master/opencv/data/lena.bmp
!wget https://raw.githubusercontent.com/MyDearGreatTeacher/AISec_2020/master/opencv/data/Lenna.jpg
!ls -al

--2020-05-14 06:24:16--  https://raw.githubusercontent.com/MyDearGreatTeacher/AISec_2020/master/opencv/data/Lenna.jpg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 160012 (156K) [image/jpeg]
Saving to: ‘Lenna.jpg’

Lenna.jpg           100%[===================>] 156.26K  --.-KB/s    in 0.02s   

2020-05-14 06:24:16 (6.62 MB/s) - ‘Lenna.jpg’ saved [160012/160012]

total 472
drwxr-xr-x 1 root root   4096 May 14 06:24  .
drwxr-xr-x 1 root root   4096 May 14 06:19  ..
drwxr-xr-x 1 root root   4096 May  8 16:16  .config
-rw-r--r-- 1 root root  66614 May 14 06:20  lena.bmp
-rw-r--r-- 1 root root  66614 May 14 06:21  lena.bmp.1
-rw-r--r-- 1 root root 160012 May 14 06:24  Lenna.jpg
-rw-r--r-- 1 root root 160012 May 14 06:23 'Lenna.jpg?raw=true'
drwxr-xr-x 1 root root   

In [13]:
# -*- coding: utf-8 -*-

#lena=cv2.imread("lena.bmp")
lena=cv2.imread("Lenna.jpg")
#lena=cv2.imread("Lenna.jpg")==>error
print(lena)

[[[125 137 225]
  [130 137 224]
  [125 137 225]
  ...
  [125 149 233]
  [121 145 229]
  [101 115 211]]

 [[125 137 225]
  [130 137 224]
  [125 137 225]
  ...
  [125 149 233]
  [121 145 229]
  [101 115 211]]

 [[125 137 225]
  [130 136 225]
  [127 137 225]
  ...
  [125 149 233]
  [118 144 228]
  [101 115 211]]

 ...

 [[ 63  28  92]
  [ 61  26  90]
  [ 65  28  92]
  ...
  [ 79  63 157]
  [ 78  65 167]
  [ 76  62 164]]

 [[ 60  21  83]
  [ 59  23  89]
  [ 65  26  94]
  ...
  [ 81  67 168]
  [ 79  70 174]
  [ 80  67 177]]

 [[ 58  22  82]
  [ 58  30  90]
  [ 64  30  95]
  ...
  [ 82  71 175]
  [ 77  71 180]
  [ 80  74 183]]]


In [11]:
type(lena)

numpy.ndarray